books = [
  {
    "_id":279,
    "author_details":"Peterson, Joseph H.",
    "title":"Lesser Key Of Solomon, The",
    "isbn":"157863220X",
    "publisher":"Weiser Books",
    "date_published":"2001-07-17",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"",
    "pages":320,
    "notes":"",
    "list_price":50.0,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Hardcover",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"Compiled from original manuscripts and fragments in the British Museum Library, Joseph Peterson's new presentation is the most complete and accurate edition of this famous magical grimoire, \"The Lesser Key of Solomon the King.\" He goes to great length to establish the provenance of each part, and possible derivative works, including critical analyses of all major variations, utilizing fresh translations of earlier magical texts such as Johann Trithemius's Steganographia, The Archidoxes of Magic by Paracelsus, and newly discovered Hebrew manuscripts of the original Key of Solomon. Abundantly illustrated, Peterson includes reproductions of the original magical circles, tools, and seals of the spirits with variations of certain drawings from various sources and notae missing from earlier editions. Source list. Appendicies. Index.",
    "genre":"Occult",
    "language":"English",
    "book_uuid":"9ca587139ca51fbac7725dbc7ab66655",
    "FIELD31":""
  },
  {
    "_id":52,
    "author_details":"Kramer, Heinrich|Sprenger, Jakob|Summers, Montague",
    "title":"Malleus Maleficarum, The",
    "isbn":"9780486228020",
    "publisher":"Dover Publications",
    "date_published":"1971-06-01",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"Dover Occult",
    "pages":278,
    "notes":"",
    "list_price":15.95,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Paperback",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"Full text of most important witchhunter's \"bible,\" used by both Catholics and Protestants. First published in 1486, the book includes everything known at the time about cults, illicit sex, dealings with the devil, and more.",
    "genre":"Social Science / General",
    "language":"English",
    "book_uuid":"b67bdb2e7b162af47d0a9014a5b02a39",
    "FIELD31":""
  },
  {
    "_id":419,
    "author_details":"Moore, Alan|Campbell, Eddie|Moor, Alan|Cambell, Eddie",
    "title":"From Hell",
    "isbn":"9780958578349",
    "publisher":"Top Shelf Production",
    "date_published":"1994-01-01",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"From Hell",
    "pages":572,
    "notes":"",
    "list_price":35.0,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Paperback",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"FROM HELL is the story of Jack the Ripper, perhaps the most infamous man in the annals of murder. Detailing the events leading up to the Whitechapel killings and the cover-up that followed, FROM HELL is a meditation on the mind of a madman whose savagery and violence gave birth to the 20th century. The serialized story, presented in its entirety in this volume, has garnered widespread attention from critics and scholars. Often regarded as one of the most significant graphic novels ever published, FROM HELL combines meticulous research with educated speculation, resulting in a masterpiece of historical fiction both compelling and terrifying. This new edition, which has been completely re-mastered, is certainly the finest edition of the book produced to date.",
    "genre":"Fiction / Mystery & Detective / General",
    "language":"English",
    "book_uuid":"54389cf13c5e8dd57134b0ee59ca838e",
    "FIELD31":""
  },
  {
    "_id":418,
    "author_details":"Dahl, Roald",
    "title":"Umbrella Man and Other Stories, The",
    "isbn":"9780142400876",
    "publisher":"Speak",
    "date_published":"2004-01-19",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"",
    "pages":288,
    "notes":"",
    "list_price":8.99,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Paperback",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"Is it really possible to invent a machine that does the job of a writer? What is it about the landlady's house that makes it so hard for her guests to leave? Does Sir Basil Turton value most his wife or one of his priceless sculptures? These compelling tales are a perfect introduction to the adult writing of a storytelling genius.",
    "genre":"Juvenile Fiction / Short Stories",
    "language":"English",
    "book_uuid":"9ca51238acb4163c77fda0422b17f484",
    "FIELD31":""
  },
  {
    "_id":423,
    "author_details":"Conarroe, Joel|Whitman, Walt|Dickinson, Emily|Stevens, Wallace|Williams, William Carlos|Frost, Robert|Hugh, Langston",
    "title":"Six American Poets",
    "isbn":"9780679406891",
    "publisher":"Random House",
    "date_published":"1991-11-12",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"",
    "pages":281,
    "notes":"",
    "list_price":27.5,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Hardcover",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"Here are the most enduring works of six great American poets, collected in a single authoritative volume. From the overflowing pantheism of Walt Whitman to the exquisite precision of Emily Dickinson; from the democratic clarity of William Carlos Williams to the cerebral luxuriance of Wallace Stevens; and from Robert Frost's deceptively homespun dramatic monologues to Langston Hughes's exuberant jazz-age lyrics, this anthology presents the best work of six makers of the modern American poetic tradition. Six American Poets includes 247 poems, among them such famous masterpieces as \"I Hear America Singing,\" \"The Idea of Order at Key West,\" \"The Dance,\" and \"Mending Wall,\" as well as lesser-known works. With perceptive introductory essays by the distinguished scholar Joel Conarroe and selections that capture the distinctive voices and visions of its authors, this volume is an invaluable addition to any poetry library.From the Trade Paperback edition.",
    "genre":"Poetry / American / General",
    "language":"English",
    "book_uuid":"0f55ddbbb77fff4614508bd36a9435cd",
    "FIELD31":""
  },
  {
    "_id":317,
    "author_details":"Pynchon, Thomas",
    "title":"Crying Of Lot 49, The",
    "isbn":"9780060913076",
    "publisher":"Harper Perennial",
    "date_published":"2006-11-07",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"Perennial Fiction Library",
    "pages":152,
    "notes":"",
    "list_price":13.99,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Paperback",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"The highly original satire about Oedipa Maas, a woman who finds herself enmeshed in a worldwide conspiracy, meets some extremely interesting characters, and attains a not inconsiderable amount of self knowledge.",
    "genre":"Fiction / Classics",
    "language":"English",
    "book_uuid":"9b2699639ab623ac721e9efbba5d5c99",
    "FIELD31":""
  },
  {
    "_id":383,
    "author_details":"Waite, Arthur Edward",
    "title":"Pictorial Key to the Tarot",
    "isbn":"9780877282181",
    "publisher":"Weiser Books",
    "date_published":"1975-10-01",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"",
    "pages":352,
    "notes":"",
    "list_price":16.95,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Paperback",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"The classic text for the Rider-Waite deck. Discusses the major and minor arcana, what each card means, reversed card meanings, and how to do a basic reading.",
    "genre":"Body, Mind & Spirit / Divination / Tarot",
    "language":"English",
    "book_uuid":"e7271bcb1a6ad67af3d0383baa10d4f0",
    "FIELD31":""
  },
  {
    "_id":485,
    "author_details":"Faraday, Michael",
    "title":"Experimental Researches in Electricity",
    "isbn":9780486435053,
    "publisher":"Dover Publications",
    "date_published":"2004-07-15",
    "rating":"0",
    "bookshelf_id":"1,2,",
    "bookshelf":"Default,to-read,",
    "read":"0",
    "series_details":"",
    "pages":368,
    "notes":"",
    "list_price":19.95,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Paperback",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"Michael Faraday (1791-1867) was the greatest physicist of the nineteenth century, a pioneer in experimentation in the fields of electricity and magnetism. He is best known for his discovery of the principle of electromagnetic induction and the laws of electrolysis. In Experimental Researches in Electricity, first published in three volumes between 1839 and 1855, Faraday discusses the inquiries that led to his development of the first dynamo (the precursor of modern dynamos and generators), and his establishment of the foundations of classical field theory. His descriptions contain scarcely a hint of mathematics, and he relates the progress of his experiments in direct, clear language. Using the primitive tools available to him in his time, in conjunction with his great imaginative gifts, Faraday explains how he arrived at his profound conclusions with stunning simplicity.\"The writing is interesting and the expositions are impressive.\" - Florida Scientist. 1914 edition.",
    "genre":"Science / Physics / Electricity",
    "language":"English",
    "book_uuid":"97b3bd24386a8ca4f036db779c4694ef",
    "FIELD31":""
  },
  {
    "_id":232,
    "author_details":"Stoppard, Tom",
    "title":"Arcadia",
    "isbn":9780571169344,
    "publisher":"Faber & Faber",
    "date_published":"1993-05-10",
    "rating":"0",
    "bookshelf_id":"1,",
    "bookshelf":"Default,",
    "read":"0",
    "series_details":"",
    "pages":112,
    "notes":"",
    "list_price":15.0,
    "anthology":"0",
    "location":"",
    "read_start":"",
    "read_end":"",
    "format":"Paperback",
    "signed":"0",
    "loaned_to":"",
    "anthology_titles":"",
    "description":"Arcadia takes us back and forth between the nineteenth and twentieth centuries, ranging over the nature of truth and time, the difference between the Classical and the Romantic temperament, and the disruptive influence of sex on our orbits in life. Focusing on the mysteries-romantic, scientific, literary-that engage the minds and hearts of characters whose passions and lives intersect across scientific planes and centuries, it is \"Stoppard's richest, most ravishing comedy to date, a play of wit, intellect, language, brio and ... emotion. It's like a dream of levitation: you're instantaneously aloft, soaring, banking, doing loop-the-loops and then, when you think you're about to plummet to earth, swooping to a gentle touchdown of not easily described sweetness and sorrow ... Exhilarating\" (Vincent Canby, The New York Times).",
    "genre":"",
    "language":"French",
    "book_uuid":"95d097744b14d2d2744050d5c6ceebdb",
    "FIELD31":""
  }
]
